[2024-11-10T22:41:50.971+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T22:41:50.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-10T22:41:49.251123+00:00 [queued]>
[2024-11-10T22:41:50.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-10T22:41:49.251123+00:00 [queued]>
[2024-11-10T22:41:50.989+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T22:41:50.995+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-10 22:41:49.251123+00:00
[2024-11-10T22:41:51.001+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1990) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T22:41:51.004+0000] {standard_task_runner.py:63} INFO - Started process 1992 to run task
[2024-11-10T22:41:51.004+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-10T22:41:49.251123+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpssxuebz8']
[2024-11-10T22:41:51.005+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask dbt_run
[2024-11-10T22:41:51.038+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-10T22:41:49.251123+00:00 [running]> on host 64c676815d01
[2024-11-10T22:41:51.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T22:41:49.251123+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T22:41:49.251123+00:00'
[2024-11-10T22:41:51.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T22:41:51.083+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-10T22:41:51.084+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/Documents/***/sjsu-data226/build_lab2/dbt run --profiles-dir /Documents/***/sjsu-data226/build_lab2 --project-dir /Documents/***/sjsu-data226/build_lab2']
[2024-11-10T22:41:51.084+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T22:41:51.084+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
                       ^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1872, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 818, in fsencode
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-11-10T22:41:51.090+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-10T22:41:49.251123+00:00, execution_date=20241110T224149, start_date=20241110T224150, end_date=20241110T224151
[2024-11-10T22:41:51.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task dbt_run (expected str, bytes or os.PathLike object, not NoneType; 1992)
[2024-11-10T22:41:51.102+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-10T22:41:51.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T22:41:51.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
