[2024-11-10T20:35:13.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T20:35:13.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.return_last_90d_price manual__2024-11-10T20:34:53.013827+00:00 [queued]>
[2024-11-10T20:35:13.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline_STOCK_ETL.return_last_90d_price manual__2024-11-10T20:34:53.013827+00:00 [queued]>
[2024-11-10T20:35:13.207+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T20:35:13.213+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): return_last_90d_price> on 2024-11-10 20:34:53.013827+00:00
[2024-11-10T20:35:13.224+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline_STOCK_ETL', 'return_last_90d_price', 'manual__2024-11-10T20:34:53.013827+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_ETL_Lab2.py', '--cfg-path', '/tmp/tmpmhrwvvxo']
[2024-11-10T20:35:13.227+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask return_last_90d_price
[2024-11-10T20:35:13.226+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-10T20:35:13.228+0000] {standard_task_runner.py:63} INFO - Started process 1446 to run task
[2024-11-10T20:35:13.258+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline_STOCK_ETL.return_last_90d_price manual__2024-11-10T20:34:53.013827+00:00 [running]> on host 599a8e9540bd
[2024-11-10T20:35:13.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline_STOCK_ETL' AIRFLOW_CTX_TASK_ID='return_last_90d_price' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T20:34:53.013827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T20:34:53.013827+00:00'
[2024-11-10T20:35:13.374+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T20:35:13.394+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T20:35:13.395+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_pipeline_ETL_Lab2.py", line 35, in return_last_90d_price
    vantage_api_key = Variable.get('apikey')
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable apikey does not exist'
[2024-11-10T20:35:13.438+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Pipeline_STOCK_ETL, task_id=return_last_90d_price, run_id=manual__2024-11-10T20:34:53.013827+00:00, execution_date=20241110T203453, start_date=20241110T203513, end_date=20241110T203513
[2024-11-10T20:35:13.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task return_last_90d_price ('Variable apikey does not exist'; 1446)
[2024-11-10T20:35:13.454+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-10T20:35:13.477+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T20:35:13.479+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
