[2024-11-10T23:11:52.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T23:11:52.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.print_aa_variable manual__2024-11-10T23:11:51.732346+00:00 [queued]>
[2024-11-10T23:11:52.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.print_aa_variable manual__2024-11-10T23:11:51.732346+00:00 [queued]>
[2024-11-10T23:11:52.688+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T23:11:52.695+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): print_aa_variable> on 2024-11-10 23:11:51.732346+00:00
[2024-11-10T23:11:52.707+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'print_aa_variable', 'manual__2024-11-10T23:11:51.732346+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpg_h92v9f']
[2024-11-10T23:11:52.711+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask print_aa_variable
[2024-11-10T23:11:52.711+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2513) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-10T23:11:52.712+0000] {standard_task_runner.py:63} INFO - Started process 2515 to run task
[2024-11-10T23:11:52.758+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.print_aa_variable manual__2024-11-10T23:11:51.732346+00:00 [running]> on host 599a8e9540bd
[2024-11-10T23:11:52.815+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='print_aa_variable' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T23:11:51.732346+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T23:11:51.732346+00:00'
[2024-11-10T23:11:52.816+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T23:11:52.830+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-10T23:11:52.831+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "The value of AA is: $DBT_ACCOUNT,$DBT_ROLE,$DBT_DATABASE,$DBT_WAREHOUSE,$DBT_USER,$DBT_TYPE,$DBT_SCHEMA,$DBT_PROJECT_DIR"']
[2024-11-10T23:11:52.832+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T23:11:52.833+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
                       ^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1872, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 818, in fsencode
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-11-10T23:11:52.840+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=print_aa_variable, run_id=manual__2024-11-10T23:11:51.732346+00:00, execution_date=20241110T231151, start_date=20241110T231152, end_date=20241110T231152
[2024-11-10T23:11:52.845+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task print_aa_variable (expected str, bytes or os.PathLike object, not NoneType; 2515)
[2024-11-10T23:11:52.854+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-10T23:11:52.864+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T23:11:52.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
